/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocIdRouteImport } from './routes/$docId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocIdIndexRouteImport } from './routes/$docId.index'
import { Route as DocIdModeRouteImport } from './routes/$docId.$mode'

const DocIdRoute = DocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdIndexRoute = DocIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocIdRoute,
} as any)
const DocIdModeRoute = DocIdModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => DocIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$docId': typeof DocIdRouteWithChildren
  '/$docId/$mode': typeof DocIdModeRoute
  '/$docId/': typeof DocIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$docId/$mode': typeof DocIdModeRoute
  '/$docId': typeof DocIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$docId': typeof DocIdRouteWithChildren
  '/$docId/$mode': typeof DocIdModeRoute
  '/$docId/': typeof DocIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$docId' | '/$docId/$mode' | '/$docId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$docId/$mode' | '/$docId'
  id: '__root__' | '/' | '/$docId' | '/$docId/$mode' | '/$docId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocIdRoute: typeof DocIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$docId': {
      id: '/$docId'
      path: '/$docId'
      fullPath: '/$docId'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$docId/': {
      id: '/$docId/'
      path: '/'
      fullPath: '/$docId/'
      preLoaderRoute: typeof DocIdIndexRouteImport
      parentRoute: typeof DocIdRoute
    }
    '/$docId/$mode': {
      id: '/$docId/$mode'
      path: '/$mode'
      fullPath: '/$docId/$mode'
      preLoaderRoute: typeof DocIdModeRouteImport
      parentRoute: typeof DocIdRoute
    }
  }
}

interface DocIdRouteChildren {
  DocIdModeRoute: typeof DocIdModeRoute
  DocIdIndexRoute: typeof DocIdIndexRoute
}

const DocIdRouteChildren: DocIdRouteChildren = {
  DocIdModeRoute: DocIdModeRoute,
  DocIdIndexRoute: DocIdIndexRoute,
}

const DocIdRouteWithChildren = DocIdRoute._addFileChildren(DocIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocIdRoute: DocIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
